### ISSUE TITLE
Working agreement documentation

### ISSUE THREAD

**Issue by no-comma** [aalto-grades/base-repository#10]
Best practices etc.

**Comment by lakooi** [comment]
I updated some of our initial working agreements in the document, that were made in our first kickoff meeting. Mostly regarding work practices.

**Comment by no-comma** [comment]
Perhaps we could write a public `CONTRIBUTING.md` with guidelines for issues, code style, commit messages, pull requests, etc.

**Comment by lakooi** [comment]
Do you think this could be a case for a new story for next sprint? My opinion would be to  be against extending the scope of existing stories during the sprint, we can talk about this after todays daily with the team.
