### ISSUE TITLE
API Specification

### ISSUE THREAD

**Issue by no-comma** [aalto-grades/base-repository#133]
As a developer, I want the backend API to be specified, so their usage is similar and documented.

DoD: Swagger documentation exists for API endpoints

- [x] Specification ideation
- [x] Writing swagger documentation
  - [x] Auth @Gskartwii 
  - [x] Course @no-comma
  - [x] Course instance @no-comma 
  - [x] Sisu @no-comma
  - [x] User @no-comma 
- [x] Swagger environment setup

**Comment by lakooi** [comment]
https://github.com/aalto-grades/base-repository/pull/141, implements the following

1. Sets up swagger with the following API's having correct response information: 
- GET: /v1/courses/{courseId}
- GET: /v1/instances/{instanceId}
- GET: /v1/user/:userId/courses

2. Describes that Routes with POST contain a requestBody, but does not elaborate the content of those
3. Does not go into detail on API's fetching information from SISU
4. Does not go into detail on authentication APIs

TODO

- [ ] Responses for SISU API
- [ ] requestBodies + Responses for POST routes
- [ ] Authentication API responses + requestbodies
- [ ] Adding more specification than 200 responses
