### ISSUE TITLE
EPIC: Design initial data model

### ISSUE THREAD

**Issue by PasiSa** [aalto-grades/base-repository#14]
Design and implement initial data model for the system. It is likely that we need to iterate and adjust the model as the system develops, but the basic concepts probably include at least the following:

Course
- Course code, name

Course instance
- ==> Course
- Instance name (e.g. fall 2022)
- Teachers (==> User)
- Start / end time

User
- Name
- Email
- Student ID
- Role (Student/Teacher/sysadmin)  -- may not be direct table member, because e.g. teacher role is respective to specific course

Grade (this needs some thought: student will have the final grade for each course, that is calculated from partial grades. Partial grades are in turn calculated from exercise/exam/etc. points. In principle there is an hierarchical structure of points/grades)
- ==> Course instance
- Expiry time

Goal: Diagram of the data model, with main attributes for each class

- [ ] #31

**Comment by lakooi** [comment]
Estimate 5

**Comment by viivi-uhari** [comment]
Design with frontend developers
