### ISSUE TITLE
EPIC: Basic user management

### ISSUE THREAD

**Issue by PasiSa** [aalto-grades/base-repository#15]
Implement a way to create new user accounts and log in using existing user accounts. Simple local sign in is sufficient for now, but later on external authentication methods should be the primary login method (e.g., using Aalto IdP). Users should be associated with name, email. They also have role respective to course (teacher/student). Some users are sysadmins with full rights.

Goal: UI to sign up as a new user (with needed information), or to log in as an existing user

- [x] #28 
- [x] #36 
- [x] #55 
- [x] #57 
- [x] #58

**Comment by viivi-uhari** [comment]
UI elements, API (+ user model), backend authentication (tokens). During sign up specify if student or teacher etc.

**Comment by viivi-uhari** [comment]
Estimate 8
