### ISSUE TITLE
EPIC: Basic front page (teacher's perspective)

### ISSUE THREAD

**Issue by PasiSa** [aalto-grades/base-repository#16]
Develop initial version of "front page" that open after user has logged in. The front page should, at least, show the list of courses and course instances the teacher is involved in

- [x] #23
- [x] #26 
- [x] #35 
- [x] #72 
- [x] #59 
- [x] #61 
- [x] #62 
- [x] #63

**Comment by viivi-uhari** [comment]
- [ ] Design basic front page for teacher view (Frontend)

**Comment by viivi-uhari** [comment]
Teacher's courses, toolbar, profile
