### ISSUE TITLE
Course points import using CSV

### ISSUE THREAD

**Issue by no-comma** [aalto-grades/base-repository#161]
As a teacher, I want to upload (or paste) a CSV to enter points on partial grade category for a particular course instance, to store the course progress for eventual grade calculation.

The first column of the file should be student number that identifies student. The CSV file may have multiple columns, each identifying one assignment category. Therefore, the first line of CSV file should have a heading, a short string label that helps to assign the points to right assignment. Single CSV file can have multiple columns, allowing import of several assignments at the same time, but it does not have to include all assignment categories within course instance, so the ("partial") results may be imported in multiple phases

DoD: There is an UI for importing points from file, and import succeeds with a file with multiple students. Tests and documentation exist. It would be good to test also with several hundred students

- [x] Frontend design for adding points via CSV @viivi-uhari 
- [x] Frontend implementation for adding points via CSV @marillam 
- [x] API for adding grade data through a CSV file @jj-stigell 
- [x] Functionality for recording student points for attainments @jj-stigell 
- [x] Database design for storing student's points for attainments @jj-stigell 
- [X] Meeting about storing assignment points in database @jj-stigell @Tonits @no-comma

**Comment by marillam** [comment]
- Frontend implementation done without connection to backend
