### ISSUE TITLE
Basic course grade calculation

### ISSUE THREAD

**Issue by no-comma** [aalto-grades/base-repository#178]
As a teacher I want to trigger grade calculation using the formula selected for the current course instance, to determine the final course grades.

Teacher should be able to trigger this manually, when she/he determines that the assignments are now completed. Also recalculation should be possible, in case assignment points change later on, or new points come late. Assignment categories should have labels that are used to match points also from earlier course instances (within a specified time period). The system should be able to show and propose the possible assignments to use in calculation, considering their expiry date.

DoD: Grade calculation can be completed and also redone if points have been updated. Has been tested with multiple consecutive calculation cycles, also with large numbers of students.

- [x] Frontend implementation for calculating grades @kiiamakir 
- [x] API for calculating grades in backend @Gskartwii @no-comma 
- [x] TypeScript function for calculating weighted average @Gskartwii 
- [x] Frontend + Backend meeting regarding points and formula attributes
- [x] Frontend refactor of formula attributes @kiiamakir

**Comment by lakooi** [comment]
- Typescript function close to completion
- Route definition is clear
- Frontend button done
