### ISSUE TITLE
User Logging Out on Pressing Aalto-Grades

### ISSUE THREAD

**Issue by lakooi** [aalto-grades/base-repository#186]
Perceived behaviour in the production environment

Source URL: https://aalto-grades.cs.aalto.fi

Problem: On pressing the aalto-grades button on top left of the page, the user is moved to the log in screen instead of being moved back to the main page of website.

**Comment by no-comma** [comment]
I can't reproduce this problem. I tried with an admin and teacher accounts at https://aalto-grades.cs.aalto.fi/ and locally with an admin account.

@jj-stigell Can you reproduce this? If not, this has probably been fixed already.

**Comment by jj-stigell** [comment]
this one is fixed
