### ISSUE TITLE
API to get all attainments of an assessment model

### ISSUE THREAD

**Issue by jj-stigell** [aalto-grades/base-repository#213]
API endpoint to fetch all available attainments of an assessment model.

**Comment by no-comma** [comment]
API endpoint: `GET /v1/course/:courseId/instances/:instanceId/attainments`

Retrieves all of the attainments of a course instance as a tree. Equivalent to the following endpoint with the difference that there is no need to know the root attainment's ID: `GET /v1/course/:courseId/instances/:instanceId/attainments/:attainmentId?tree=descendants`
