### ISSUE TITLE
Study attainment expiry date inconsistency

### ISSUE THREAD

**Issue by jj-stigell** [aalto-grades/base-repository#219]
Expiry date in study attainments editing view doesn’t match the one shown on course instance view. Could be caused by the mock data still used in the frontend

**Comment by no-comma** [comment]
`/course-view/1` shows the expiry date 14.09.2024 for Exercises, and clicking on edit still shows its expiry date is the 14th of September 2024. Updating Exercises to expire in 2025 in `mockAttainmentsClient.tsx` also updates the UI to 2025 in both places.

There doesn't seem to be any problem as far as I can tell.
