### ISSUE TITLE
EPIC: UI for setting course attributes and course structure

### ISSUE THREAD

**Issue by viivi-uhari** [aalto-grades/base-repository#24]
Teacher should have an UI to set up a new course, or new instance of an existing course, along with the relevant attributes: other teachers, start/end times, and the grading structure. Some of these attributes can be fetched from the SISU APIs, see other issue (#ID to be determined).

Goal: Basic UI exists, with few editable fields to set the course attributes.

- [x] #32 
- [x] #33 
- [x] #29 
- [x] #30

**Comment by no-comma** [comment]
This issue is to be replaced with more specific ones.
