### ISSUE TITLE
Logging in error handler middleware

### ISSUE THREAD

**Issue by no-comma** [aalto-grades/base-repository#244]
The error handler middleware should log errors somewhere, so that controllers will be easier to debug.

Maybe logging in the console for dev and test environments, otherwise something else?

**Comment by PasiSa** [comment]
I have forgot to add a more general issue on logging to the MVP2 milestone. In addition to errors, all relevant events (grade adjustments, user access changes, etc.) should be logged according to Aalto security policies. There is a guideline document about what information should be included in log message, but for example there should be username and IP address, so there is are some starting points to track down suspicious activity if such happens.

**Comment by PasiSa** [comment]
Added: https://github.com/aalto-grades/base-repository/issues/247

**Comment by no-comma** [comment]
This is practically done for the problem I wanted to solve, more detailed error logging can be tracked in the future in #247 or some new issue.
