### ISSUE TITLE
Where to access list of all courses

### ISSUE THREAD

**Issue by no-comma** [aalto-grades/base-repository#260]
There is now a view for listing all existing courses, and other than logging in as an admin, there is no way to directly access it from the UI. A regular user may wish to also see a list of all courses in some cases, so where should the option to do so be located?

**Comment by jj-stigell** [comment]
From admin point of view, I was thinking this could be be in the name dropdown menu e.g. "johd doe" => "all course", "create a course", "logout". These extra buttons can be easily rendered based on system level role.

**Comment by no-comma** [comment]
Right now the list of all courses has been integrated to the front page showing the courses a user has some role in, so it is discoverable from the UI alone.
