### ISSUE TITLE
Date entry while uploading grades via CSV

### ISSUE THREAD

**Issue by no-comma** [aalto-grades/base-repository#294]
When a teacher is uploading a grade CSV, the frontend should parse attainment tags from the CSV and allow the teacher to set the date and expiry date for each attainment, which are sent in the body to the server.

**Comment by PasiSa** [comment]
Just pinning a comment here to remind about this issue. When importing from CSV, there is currently no way to set the attainment completion date. When uploading a CSV with grades, there could be a dialog that let's the teacher to pick the date.
