### ISSUE TITLE
Choose database technology

### ISSUE THREAD

**Issue by no-comma** [aalto-grades/base-repository#3]
Could be done 2.11.

**Comment by Tonits** [comment]
PostgreSQL chosen

**Comment by lakooi** [comment]
- Backend:
    - NodeJS backend
    - ExpressJS vs NestJS backend, was thought, express chosen for good extendability
    - Passport for authentication in the future 
    - Typescript for static typing.
    - Relational DB -> PostgreSQL
    - ORM in between DB and express.
