### ISSUE TITLE
Create data model diagrams

### ISSUE THREAD

**Issue by Tonits** [aalto-grades/base-repository#31]
Draw UML/EER diagram from the data model

**Comment by jj-stigell** [comment]
Data model diagram(read only)
https://dbdiagram.io/d/63721198c9abfc6111727012

**Comment by jj-stigell** [comment]
Updated diagram

![Image](https://user-images.githubusercontent.com/63514007/204742249-67acd8a7-6324-44be-b9ed-09ee59cc6165.png)
