### ISSUE TITLE
Display grades of student for each attainment in an assessment model

### ISSUE THREAD

**Issue by no-comma** [aalto-grades/base-repository#356]
When clicking a student in the course result view, it should open a dialog which shows the given student's grades for every attainment in the assessment model in a similar tree structure as attainments are displayed in the course view.

- [x] Dialog in frontend
- [x] API endpoint to get all grades of a student for an assessment model as a tree

**Comment by jj-stigell** [comment]
GET /v1/courses/:courseId/assessment-models/:assessmentModelId/grades/:userId to get all user grades for assessment model
