### ISSUE TITLE
Server-side security

### ISSUE THREAD

**Issue by no-comma** [aalto-grades/base-repository#371]
Take measures against possible security issues such as CSRF and XSS.

- [x] Include [Helmet](https://helmetjs.github.io/) ExpressJS middleware to the API. #415 
- [x] Cyber security review with Aalto IT
- [x] brute-force attacks against authorization, if Aalto grades own login system will be used

**Comment by jj-stigell** [comment]
ExpressJs best practices on [security](https://expressjs.com/en/advanced/best-practice-security.html)

**Comment by bntti** [comment]
Brute-force attack tests are probably not needed because we will be throttling the login attempts. Also we have requirements for admin password strength that should make passwords hard to crack (even with the hash)
