### ISSUE TITLE
Use latest attainment date as Sisu CSV date

### ISSUE THREAD

**Issue by no-comma** [aalto-grades/base-repository#424]
The option of using the latest attainment date as the date in the Sisu CSV came up. Should this be done or should the teacher still need to set it manually?

**Comment by no-comma** [comment]
The teacher should not have to set a completion date when exporting a Sisu CSV. The date is automatically determined by the latest completed attainment grade for a given student.

**Comment by gubo97000** [comment]
'If not provided, the default will be course instance ending date.'
Should this text be changed to 
'If not provided, for each student their latest attainment date will be used.'

![image](https://github.com/aalto-grades/base-repository/assets/23000960/a1113778-c2a3-4bd2-8e90-4a7157299d9f)
