### ISSUE TITLE
Confusing messages about unsaved changes in the course results view

### ISSUE THREAD

**Issue by no-comma** [aalto-grades/base-repository#442]
When students have been selected in the course results view, the "return to course view" button turns red and shows a tooltip message:

> You have selected students, these selections will be lost if not saved.

This tooltip doesn't make sense, because the selections can't be saved anyway. This should either be updated to something more appropriate, or it should be evaluated whether the unsaved changes dialog is even needed in the results view in the first place.

**Comment by jj-stigell** [comment]
remove tooltip text
