### ISSUE TITLE
Final grades should appear as integers

### ISSUE THREAD

**Issue by PasiSa** [aalto-grades/base-repository#459]
Final grades should be integers (typically from 0 to 5), especially when exported to Sisu as CSV, but also in UI. Now, when pressing "Calculate final grades", the final grades are stored and presented as exact decimal values. They appear as decimal values also in Sisu CSV, but I assume that Sisu would not even accept other than integer values between 0 and 5 (for the majority of courses that use that as the grading scale).

**Comment by no-comma** [comment]
The easiest option would be to say that the formulas are responsible for dealing with this. But it may also make sense to include a column in attainments for whether the grades of it are integers or floats, but this still leaves the problem of rounding values, which the formulas will have to do. Rounding to the nearest integer appears to be the best default option in the absence of the formula doing something else.
