### ISSUE TITLE
Grade calculation can result in a larger grade than the max grade of an attainment

### ISSUE THREAD

**Issue by no-comma** [aalto-grades/base-repository#486]
There are no checks in place to ensure that a grade calculation function can't calculate a grade larger than the maximum grade of an attainment. How should these cases be handled? Is rounding down to the max grade sufficient? Or should an error message be returned saying that something is wrong?

**Comment by no-comma** [comment]
An error message should be returned.

**Comment by kurukimi** [comment]
It seems that indeed the final grade calculation doesn't take the max grade into consideration. Also, one can edit the grades (of sub attainments or final grade) to be over the limits. This should probably show an error also. Not sure yet whether checks are in place when importing the grades initially.
