### ISSUE TITLE
Sisu export dates should maybe not be stored in attainment grades

### ISSUE THREAD

**Issue by no-comma** [aalto-grades/base-repository#493]
**Is your feature request related to a problem? Please describe.**
It may not be a good idea to store Sisu export dates in the attainment grade table, because then this information will also be included in every other grade, even ones that will never get uploaded to Sisu and aren't even relevant for Sisu.

**Describe alternatives you've considered**
We could maybe have another table for storing this information which reference just the final grade?

**Comment by jj-stigell** [comment]
<img width="728" alt="Screenshot 2023-08-16 at 15 54 15" src="https://github.com/aalto-grades/base-repository/assets/63514007/8260cdaa-5e58-492c-831d-490b7752eb0f">

I had originally something like this on my mind, we could remove the sisuexportdate from attainment grades. We could keep history how many times grades are exported, export old batches again, etc. Now each time grade is re-exported the date is overwritten.
