### ISSUE TITLE
Expired grades should be indicated in UI

### ISSUE THREAD

**Issue by no-comma** [aalto-grades/base-repository#500]
Grades which have expired should be shown in the UI, and it should be indicated to the user that they are expired. Likely requires updating the grade tree endpoint to return whether each `GradeOption` has expired.

Related to #444

**Comment by gubo97000** [comment]
I am quite confused on how much strength should be applied to the visualization of the expiration. 
Also right now issue #444 is not really enforced, expired grade are utilized for calculating the final grade...
I don't know if this is a design choice or a bug, based on how expired grades are treated I can define a better visualization.
