### ISSUE TITLE
Individual Cypress tests

### ISSUE THREAD

**Issue by no-comma** [aalto-grades/base-repository#508]
Related to #481 

List of many (not all) end-to-end tests that should be written with Cypress.

**Login**:
- [ ] Should work and redirect to front page
- [ ] Should fail with incorrect email or password

**Front page**:
- [ ] Should show the courses the user is a teacher in
- [ ] Should allow admins to create new courses
- [ ] Should not allow anyone else to create new courses

**Course creation**:
- [ ] Should allow creating courses which show up in the courses list in the front page
- [ ] Should fail to create a course if validation fails
- [ ] Should not be shown to non-admins

**Course view**:

**Course editing**:
- [ ] Should allow admins to edit a course
- [ ] Should not allow non-admins to edit a course
- [ ] Should work correctly and show the edited data in the course view
- [ ] Should fail if validation fails

**Instance creation**:
- [ ] Should show instances from Sisu
- [ ] Should allow using a Sisu instance as a base
- [ ] Should allow creating an instance from scratch
- [ ] Should work correctly and show the created instance in the course view
- [ ] Should fail if validation fails

**Assessment model creation**:
- [ ] Should allow creating an empty assessment model
- [ ] Should allow creating an assessment model with another one as a base

**Attainment creation**:
- [ ] Should allow creating an attainment with no children
- [ ] Should allow creating an attainment with one level of subattainments
- [ ] Should allow creating an attainment with deeper levels of subattainments
- [ ] Should allow setting and configuring a formula for the "root" attainment
- [ ] Should allow setting and configuring a formula for subattainments

**Attainment editing**:
- [ ] Should allow editing the single "root" attainment
- [ ] Should allow deleting the "root" attainment and all of the attainments below it
- [ ] Should allow editing a single subattainment
- [ ] Should allow adding a single subattainment
- [ ] Should allow deleting a single subattainment with no children
- [ ] Should allow deleting a subattainment and all of the attainments below it
- [ ] Should allow editing, adding, and deleting subattainments simultaneously
- [ ] Should allow changing and configuring a formula for the "root" attainment
- [ ] Should allow setting and configuring a formula for subattainments

**Formula editing**:

**Course results**:

**Comment by jyrge** [comment]
A blocking issue occurred, while attempting to develop individual Cypress test cases.

The login with correct admin credentials succeeds, but the session is lost shortly after login (presumably after the redirection to the frontpage after logging in). I couldn't find the reason behind this, nor any working solutions to the problem.

Server log for backend shows response 200 for the POST /v1/auth/login. After that, the 401 occurs for GET /v1/auth/self-info, which should not happen with the valid session.

WIP PR #524 contains the initial attempt for writing the login tests.

**Comment by gubo97000** [comment]
The tests will be made with Playwright, following the stack of cs-it team

**Comment by bntti** [comment]
Project structure is now very different, so a new list of required tests needs to be created.
