### ISSUE TITLE
Session management

### ISSUE THREAD

**Issue by no-comma** [aalto-grades/base-repository#56]

**Comment by lakooi** [comment]
Has frontend and Backend Components.

**Comment by lakooi** [comment]
For backend: 

https://www.digitalocean.com/community/tutorials/nodejs-jwt-expressjs

https://www.geeksforgeeks.org/how-to-implement-jwt-authentication-in-express-js-app/

The second link has a sequence diagram for how I see that this should be done. 

We can store this JWT token in the cookies of the browser for example.

**Comment by lakooi** [comment]
If we implement this through a JWT approach the integration to an external identity provider should be easier.
