### ISSUE TITLE
CSV Flexible Import

### ISSUE THREAD

**Issue by gubo97000** [aalto-grades/base-repository#587]
The import function for CSV needs to accept more separators.
The main default separators from the most famous data editors should be added.

Would be nice to also add more file format to avoid problems with users.

**Comment by bntti** [comment]
csv-parse supports multiple delimiters at the same time. Maybe this could be used with all of the common delimiters. (assuming that the data doesn't contain any extra delimiter characters)
https://csv.js.org/parse/options/delimiter/
https://github.com/aalto-grades/base-repository/blob/11cdd0c1ceeefb9df6fcc416625639904ea3ab66/server/src/controllers/grades.ts#L1091-L1094

**Comment by gubo97000** [comment]
I would accept the most common one, ";" and ",". We should have problems with the data even though right now we use the attainment name instead of the id, I think for accessibility?
