### ISSUE TITLE
Improve docs about linting

### ISSUE THREAD

**Issue by kurukimi** [aalto-grades/base-repository#646]
Following the instructions given in the docs when setting up local development environment results in different linting configuration than is used in pr tests.
Does the user need to do something manually?

**Comment by bntti** [comment]
I updated the packages at some point and that changed some of the linting rules. Try running `npm ci` in all folders with a package.json, that might fix the issue.

**Comment by kurukimi** [comment]
I tried cloning a fresh repo and running npm ci atleast in server and client but running linter in those folders it had a lot more lint errors than the pr checks. I can try later again.

**Comment by bntti** [comment]
You need to also run `npm ci` in the common folder.

**Comment by bntti** [comment]
The documentation is apparently out of date for linting. Closing as duplicate (see #626)
