### ISSUE TITLE
Define frontend requirements for course/course instance information

### ISSUE THREAD

**Issue by no-comma** [aalto-grades/base-repository#70]

**Comment by kiiamakir** [comment]
**Frontend requirements**

Course

- Course code
- Course name
- Organizer/Department
- Responsible teacher(s)

Course instance

- Course code
- Course name
- Teaching period
- Starting date
- Ending date
- Type (lecture/exam)
- Grading scale (pass/fail or 0-5)
- Organizer
- Educational institution
- Responsible teacher(s)
- Credits (min and max)
- Partial assignments
    - Type
    - Description
    - Total points
    - Weight (can be a function)
    - Expiry date

**Comment by viivi-uhari** [comment]
PO approved
