### ISSUE TITLE
Product base setup

### ISSUE THREAD

**Issue by no-comma** [aalto-grades/base-repository#8]
After tech stack has been selected, create a base that displays something like "Hello world" when run.

Depends on #1 
Depends on #2

**Comment by no-comma** [comment]
What kind of a directory structure should we use? `/client` for frontend and `/server` for backend, each with necessary subdirectories?

**Comment by viivi-uhari** [comment]
@no-comma 's proposal for the directory structure seems good! We could discuss how to link the frontend to the backend on Monday after the daily. At this point running the application locally and using different ports for frontend and backend could be a simple and working approach.

**Comment by viivi-uhari** [comment]
Pull requests made for frontend #19 and backend #18 bases.
